### ISSUE TITLE
"Could not open input file"

### ISSUE THREAD

**Issue by LOCOMODDING** [ChuckTSI/BetterThanNothingWebInterface#10]
Hello,

I am having issues after creating a docker image and container. I ran the docker build and compose as instructed, but I am having the following error. Would you be able to help? I do have access to 192.168.100.1 and can view my statistics in the app. Thanks

![08dea7c79e468335660ef60b01a4ad29](https://user-images.githubusercontent.com/13503672/111022090-83cbe980-8385-11eb-8767-ed2e83da95fb.png)

![57a44c9bbe7e0378eb27d9d18fc51002](https://user-images.githubusercontent.com/13503672/111022104-a3fba880-8385-11eb-9b08-287d6eb0b9a9.png)

**Comment by ChuckTSI** [comment]
I'm sorry. I didn't write the docker container. My knowledge is limited on them. You could ask: https://github.com/dbjohnson who wrote it.

Check the config file and make sure the paths in it point to where the files are in the container.  Which I think is /var/ww/html/btnwi

**Comment by LOCOMODDING** [comment]
Okay I will check. I was having an issues where the CLI is constantly
logging as well, and I can’t get it to stop logging the error without
stopping the container. Thanks for responding.

**Comment by LOCOMODDING** [comment]
@dbjohnson, do you have any information on the error above by chance my friend? Thank you!

**Comment by patyork** [comment]
@LOCOMODDING 

I haven't looked too far into the fix, but the "why" is a working directory issue. **Adding this line to Dockerfile** in the clone step will duplicate the scripts/data/etc to the "html" directory which the BTNWI is expecting:

`COPY . /var/www/html`

**Comment by LOCOMODDING** [comment]
Thank you @patyork, that solved the issue!

**Comment by patyork** [comment]
As @ChuckTSI alluded to, there is a config.inc.php file that has some config parameters I missed. https://github.com/ChuckTSI/BetterThanNothingWebInterface/blob/b906b0f6fb5de7670cfacfbd7089477b73308b18/config.inc.php#L5
can be changed to
`$_CONFIG["path"] = '/var/www/html/btnwi';`
or
`$_CONFIG["path"] = '/var/www/html/BetterThanNothingWebInterface';`
which will work with the current Docker config file (and serve the BTNWI as a subfolder http://localhost/btnwi or http://localhost/BetterThanNothingWebInterface, which you may want).

Option 2 is to change https://github.com/ChuckTSI/BetterThanNothingWebInterface/blob/b906b0f6fb5de7670cfacfbd7089477b73308b18/Dockerfile#L12
to
`COPY . /var/www/html`
and remove lines 13 and 14 to serve it at the root, and with no change to the PHP config file mentioned above.
